export const API_HOME = "/delivery-service/api/v1/";
export const PACKAGE_SIZES = API_HOME + "package-sizes";
export const ORDERS = API_HOME + "orders";
export const PACKAGE_OPTIONS = API_HOME + "package-options";
export const ATTRIBUTES = API_HOME + "attributes";
export const LOGIN = API_HOME + "login";
export const REGISTER = API_HOME + "register";
export const CURRENT_USER = API_HOME + "current-user";
export const USER_PASSWORD = API_HOME + "user/password";
